/** Canonical route / path prefixes — frontend + backend */

export const API_ROUTES = {
  V1: '/api/v1',
  INTERNAL: '/api/internal',
  WEBHOOKS: '/api/webhooks',
  HEALTH: '/health',
  AUTH: '/auth',
  INSTITUTIONS: '/institutions',
  CAMPUSES: '/campuses',
  SCHOOLS: '/schools',
  DEPARTMENTS: '/departments',
  PROGRAMS: '/programs',
  ACADEMIC_YEARS: '/academic-years',
  SEMESTERS: '/semesters',
  SECTIONS: '/sections',
  BATCHES: '/batches',
  ACADEMIC_CALENDARS: '/academic-calendars',
  INSTITUTION_SETTINGS: '/institution-settings',
  LMS: '/lms',
  ERP: '/erp',
  EXAMINATION: '/examination',
  CODING: '/coding',
  IDE: '/ide',
  IDEATION: '/ideation',
  ANALYTICS: '/analytics',
  AUDIT: '/audit',
  USERS: '/users',
} as const;

export const APP_ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  REGISTER_INSTITUTION: '/register-institution',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  DASHBOARD: '/dashboard',
  INSTITUTION_DASHBOARD: '/institution/dashboard',
  FACULTY_DASHBOARD: '/faculty/dashboard',
  STUDENT_DASHBOARD: '/student/dashboard',
  COURSES: '/courses',
  EXAMS: '/exams',
  CODING: '/coding',
  IDE: '/ide',
  IDEATION: '/ideation',
  ANALYTICS: '/analytics',
  SETTINGS: '/settings',
  ABOUT: '/about',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  SECURITY: '/security',
  CONTACT: '/contact',
  FEATURES: '/features',
  INSTITUTION: '/institution',
  INSTITUTION_SETUP: '/institution/setup',
  INSTITUTION_PROFILE: '/institution/profile',
  INSTITUTION_CAMPUSES: '/institution/campuses',
  INSTITUTION_SCHOOLS: '/institution/schools',
  INSTITUTION_DEPARTMENTS: '/institution/departments',
  INSTITUTION_PROGRAMS: '/institution/programs',
  INSTITUTION_ACADEMIC_YEARS: '/institution/academic-years',
  INSTITUTION_SEMESTERS: '/institution/semesters',
  INSTITUTION_SECTIONS: '/institution/sections',
  INSTITUTION_BATCHES: '/institution/batches',
  INSTITUTION_CALENDAR: '/institution/calendar',
  INSTITUTION_SETTINGS: '/institution/settings',
} as const;

export const SOCKET_NAMESPACES = {
  IDE: '/ide',
  EXAM: '/exam',
  NOTIFICATIONS: '/notifications',
} as const;
