module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'frontend',
        'backend',
        'worker',
        'ui',
        'types',
        'shared',
        'config',
        'docker',
        'docs',
        'ci',
        'deps',
        'auth',
        'lms',
        'erp',
        'exam',
        'coding',
        'ide',
        'ideation',
        'analytics',
        'audit',
        'i18n',
        'repo',
      ],
    ],
    'subject-case': [2, 'never', ['pascal-case', 'upper-case']],
    'header-max-length': [2, 'always', 100],
  },
};
