/** Permission string constants — mirror @learnova/types Permission union */

export const PERMISSIONS = {
  LMS_READ: 'lms:read',
  LMS_WRITE: 'lms:write',
  LMS_MANAGE: 'lms:manage',
  ERP_READ: 'erp:read',
  ERP_WRITE: 'erp:write',
  ERP_MANAGE: 'erp:manage',
  EXAMINATION_READ: 'examination:read',
  EXAMINATION_WRITE: 'examination:write',
  EXAMINATION_MANAGE: 'examination:manage',
  EXAMINATION_PROCTOR: 'examination:proctor',
  CODING_READ: 'coding:read',
  CODING_WRITE: 'coding:write',
  CODING_SUBMIT: 'coding:submit',
  IDE_ACCESS: 'ide:access',
  IDEATION_READ: 'ideation:read',
  IDEATION_WRITE: 'ideation:write',
  ANALYTICS_READ: 'analytics:read',
  ANALYTICS_EXPORT: 'analytics:export',
  AUDIT_READ: 'audit:read',
  USERS_READ: 'users:read',
  USERS_MANAGE: 'users:manage',
  ROLES_MANAGE: 'roles:manage',
  INSTITUTION_READ: 'institution:read',
  INSTITUTION_MANAGE: 'institution:manage',
  FACULTY_READ: 'faculty:read',
  FACULTY_WRITE: 'faculty:write',
  FACULTY_MANAGE: 'faculty:manage',
  STUDENT_READ: 'student:read',
  STUDENT_WRITE: 'student:write',
  STUDENT_MANAGE: 'student:manage',
  COURSE_READ: 'course:read',
  COURSE_WRITE: 'course:write',
  COURSE_MANAGE: 'course:manage',
  ENROLLMENT_READ: 'enrollment:read',
  ENROLLMENT_WRITE: 'enrollment:write',
  ENROLLMENT_MANAGE: 'enrollment:manage',
} as const;

export type PermissionConstant = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
