export {
  objectIdSchema,
  uuidSchema,
  emailSchema,
  localeSchema,
  roleSchema,
  paginationSchema,
  searchQuerySchema,
  slugSchema,
  passwordSchema,
  registerInstitutionSchema,
  loginSchema,
  forgotPasswordSchema,
  resetPasswordSchema,
  changePasswordSchema,
  verifyEmailSchema,
  resendVerificationSchema,
  sessionIdParamsSchema,
  type PaginationInput,
  type SearchQueryInput,
  type RegisterInstitutionInput,
  type LoginInput,
  type ForgotPasswordInput,
  type ResetPasswordInput,
  type ChangePasswordInput,
  type VerifyEmailInput,
  type ResendVerificationInput,
} from '@learnova/validation';
